# yamllint configuration
# https://yamllint.readthedocs.io/

extends: default

rules:
  # Allow long lines (common in GitHub Actions)
  line-length:
    max: 200
    level: warning

  # Require document start marker
  document-start: disable

  # Allow inline mappings for readability
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1

  # Truthy values (allow yes/no, on/off)
  truthy:
    allowed-values: ["true", "false", "yes", "no", "on", "off"]
    check-keys: false

  # Comments
  comments:
    min-spaces-from-content: 1

  # Indentation
  indentation:
    spaces: 2
    indent-sequences: true

ignore: |
  node_modules/
  infra/
  .devcontainer/
